/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GButton {
        "theme": 'primary' | 'secondary' | 'outlined' | 'naked';
    }
}
declare global {
    interface HTMLGButtonElement extends Components.GButton, HTMLStencilElement {
    }
    var HTMLGButtonElement: {
        prototype: HTMLGButtonElement;
        new (): HTMLGButtonElement;
    };
    interface HTMLElementTagNameMap {
        "g-button": HTMLGButtonElement;
    }
}
declare namespace LocalJSX {
    interface GButton {
        "theme"?: 'primary' | 'secondary' | 'outlined' | 'naked';
    }
    interface IntrinsicElements {
        "g-button": GButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "g-button": LocalJSX.GButton & JSXBase.HTMLAttributes<HTMLGButtonElement>;
        }
    }
}
